# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
    sed -i "s/#ServerName www.example.com/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chown -R g=u /var/log/httpd /var/run/httpd
 

EXPOSE 8080

LABEL io.openshift.expose-services="8080:http"

ONBUILD COPY src/ /var/www/html/

USER 1001






















