# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

RUN sed -i "/s/Listen 80/Listen 8080/g" /etc/httpd/conf/https.conf && \
    sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -r g=u /var/log/httpd /var/run/httpd

EXPOSE 8080

ONBUILD COPY /src /var/www/html

LABEL io.openshift.expose-services="8080:http"

USER 1001	



